---
pagetitle: "Privacy Statement"
toc: false
---

# Privacy Statement

We appreciate your interest in using our website. The protection of personal data is our highest priority. Below, you will find information concerning the processing of your personal data and your rights when using our website.

## 1. Controller

AI-SIC <br>
Computational Humanities <br>
University of Leipzig <br>
Augustusplatz 10, Raum P 616 <br>
04109 Leipzig <br>
Phone: +49 341 97-232239 <br>
E-Mail: aniekler@informatik.uni-leipzig.de <br>

<!--

## 2. Data Protection Officer

Thomas Braatz  
Neues Augusteum  
Augustusplatz 10, Raum A218  
04109 Leipzig  
Phone: +49 341 97 - 30081  
Email: dsb@uni-leipzig.de

-->

## 2. Your Rights as a Data Subject

You have the following rights under the GDPR:

- Right of access (Art. 15 GDPR)
- Right to rectification (Art. 16 GDPR)
- Right to erasure ("right to be forgotten") (Art. 17 GDPR)
- Right to restriction of processing (Art. 18 GDPR)
- Right to data portability (Art. 20 GDPR)
- Right to object (Art. 21 GDPR)

You also have the right to lodge a complaint with a data protection supervisory authority, especially in the EU Member State of your habitual residence, place of work, or place of the alleged infringement.

## 3. Purpose and Legal Basis of Processing

We do not collect personal data unless it is necessary to provide the website.

## 4. Hosting and Log Files

Our website is hosted by **GitHub Pages**, a service provided by GitHub Inc., San Francisco, USA. When you access our website, certain information is automatically transmitted by your browser and may be stored in server log files, including:

- IP address
- Date and time of the request
- Browser type and version
- Operating system
- Referrer URL (if applicable)

For more information on GitHub’s data processing, please refer to their privacy policy:  
[https://docs.github.com/en/site-policy/privacy-policies/github-privacy-statement](https://docs.github.com/en/site-policy/privacy-policies/github-privacy-statement)

## 5. Cookies and Tracking

Our website does not use cookies or any form of tracking or analytics tools.

## 6. Automated Decision-Making, Including Profiling

No automated decision-making, including profiling as defined in Article 22 of the GDPR, takes place in connection with the use of our website.
